version: '2.1'

services:

    reverse-proxy:
        image: ${AWSPROXY}
        container_name: reverse_proxy
        depends_on:
            - lavagna
        ports: 
          - 80:80
        

    db: 
        image: mysql:5.7
        container_name: mysql_lavagna
        command: "--default-authentication-plugin=mysql_native_password"
        environment: 
            MYSQL_ROOT_PASSWORD: '123'
            #MYSQL_USER: 'root'
            #MYSQL_DATABSE: 'lavagna'
        volumes:
            - db_data:/var/lib/mysql
            - ./:/docker-entrypoint-initdb.d/
            
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 12s
            timeout: 580s
            retries: 120

    lavagna:
        image: ${AWSAPP}
        container_name: lavagna
        depends_on:
            db:
              condition: service_healthy
        ports: 
            - 8080:80
    

volumes: 
    db_data:
    reverse_proxy: