version: '2.1'

services:

    reverse-proxy:
        image: nginx:latest
        container_name: reverse_proxy
        build: ./reverse_proxy
        depends_on:
            - lavagna
        volumes:
          - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
          - ./reverse_proxy/webapp:/etc/nginx/html/static
        ports: 
          - 80:80
        

    db: 
        image: mysql:5.7
        container_name: mysql_lavagna
        command: "--default-authentication-plugin=mysql_native_password"
        environment: 
            MYSQL_ROOT_PASSWORD: '123'
            #MYSQL_USER: 'root'
            #MYSQL_DATABSE: 'lavagna'
        volumes:
            - db_data:/var/lib/mysql
            - ./DB:/docker-entrypoint-initdb.d/
            
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 12s
            timeout: 580s
            retries: 120

    lavagna:
        image: "lavagna"
        container_name: lavagna
        build: ./project
        depends_on:
            db:
              condition: service_healthy
        ports: 
            - 8080:80

    doc:
        image: "documentation"
        container_name: "doc"
        build: 
            context: ./project 
            dockerfile: Dockerfile_doc
        ports: 
            - "8081:8081"

    

volumes: 
    db_data:

